import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { UserProvider } from "@/contexts/UserContext";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "完蛋，你被AI纠缠了",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${inter.className}`}>
        <UserProvider>
          <Theme>
            <div className="h-screen">
              <Header />
              {children} {/* 主内容区域 */}
              <Footer />
            </div>
          </Theme>
        </UserProvider>
        <GoogleAnalytics gaId="G-XT4GNP697S" />
        <SpeedInsights />
      </body>
    </html>
  );
}
